jobs:
- name: initialize-app
  plan:
  - aggregate:
    - get: heroku-example
      trigger: true
  - task: create-app
    file: heroku-example/concourse/init_application.yml
    input_mapping: {source: heroku-example}
    params:
      app_name: glennbech-heroku-example
      heroku_email: ((heroku_email))
      heroku_api_token: ((heroku_api_token))

- name: deploy-infra
  plan:
  - aggregate:
    - get: heroku-example
      trigger: true
  - task: apply
    file: heroku-example/concourse/task_terraform.yml
    input_mapping: {source: heroku-example}
    params:
      github_token: ((github_token))
      command: apply
      directories: |
          .
  - put: heroku-example
    params:
      repository: with-state
      rebase: true

resources:

- name: heroku-example
  type: git
  source:
      uri: git@github.com:PGR_301-2018/heroku-example.git
      branch: master
      private_key: ((deploy_key))
